export const ERROR_CODES = {
  AUTHENTICATION_FAILED: 'AUTH_001',
  AUTHORIZATION_FAILED: 'AUTH_002',
  INVALID_INPUT: 'VAL_001',
  RESOURCE_NOT_FOUND: 'RES_001',
  RATE_LIMIT_EXCEEDED: 'RATE_001',
  AGENT_EXECUTION_FAILED: 'AGENT_001',
  TOOL_EXECUTION_FAILED: 'TOOL_001',
  LLM_API_ERROR: 'LLM_001',
  DATABASE_ERROR: 'DB_001',
  NETWORK_ERROR: 'NET_001',
} as const;

export const ERROR_MESSAGES = {
  [ERROR_CODES.AUTHENTICATION_FAILED]: 'Authentication failed',
  [ERROR_CODES.AUTHORIZATION_FAILED]: 'Authorization failed',
  [ERROR_CODES.INVALID_INPUT]: 'Invalid input provided',
  [ERROR_CODES.RESOURCE_NOT_FOUND]: 'Resource not found',
  [ERROR_CODES.RATE_LIMIT_EXCEEDED]: 'Rate limit exceeded',
  [ERROR_CODES.AGENT_EXECUTION_FAILED]: 'Agent execution failed',
  [ERROR_CODES.TOOL_EXECUTION_FAILED]: 'Tool execution failed',
  [ERROR_CODES.LLM_API_ERROR]: 'LLM API error',
  [ERROR_CODES.DATABASE_ERROR]: 'Database error',
  [ERROR_CODES.NETWORK_ERROR]: 'Network error',
} as const;
